### ISSUE TITLE
Updating .travis.yml

### ISSUE THREAD

**Issue by eddelbuettel** [docopt/docopt.R#30]
A while back someone pointed out to me that `curl http://...` fetches are not ideal, and I have been slowly converting mine (in the `.travis.yml` script) piece by to piece to do that.

As I had your repo checked too, I noticed that you still use the old old `.travis.yml` of mine.  I have one better and could send you a trivial simple PR replacing that.  Would that help?

You can of course also just leave things as they as they ain't broken ...

**Comment by edwindj** [comment]
Thanks! While it ain't broken, I think updating the travis.yml is wise. In
my other projects I use newer versions of travis.yml, but I rarely
read/update them once they work: so if you happen to have a readily
available updated travis.yml I would appreciate a PR.

Best,

Edwin

**Comment by eddelbuettel** [comment]
Deal. Will do.   I am of course aware that "my" Travis use is non-standard so I don't mean to impose it on you but as you already have an older version may as well...

I use these in my dozens of repos and they still work for me.  I find the easier shell-script-alike setup easier so I haven't bothered converting my setup.  _If it ain't broke,,,_   So PR coming shortly.

**Comment by eddelbuettel** [comment]
Commit made [in this branch](https://github.com/eddelbuettel/docopt.R/tree/feature/updated_travis) but I myself did not yet have Travis enabled for this repo, so it did not tickle.

So I created another [redundant branch off it](https://github.com/eddelbuettel/docopt.R/tree/feature/redundant_branch), added and removed a file to tickle a Travis build which is [here](https://travis-ci.org/eddelbuettel/docopt.R/builds/268674779) and which worked.  Yay!

So I'll PR this (off the original one-commit branch).  No hurry -- review on the weekend or early next week.

**Comment by eddelbuettel** [comment]
That was merged a long while ago in #31
