### ISSUE TITLE
FR: convert dashes to underscores

### ISSUE THREAD

**Issue by t-kalinowski** [docopt/docopt.R#39]
Hello,

It would be nice if `docopt(strip_names = TRUE)` would also convert command line arguments invoked like `--do-the-thing` so that from R they were accessible as `opt$do_the_thing`

**Comment by fgp** [comment]
This change breaks existing code (for example, mine https://github.com/Cibiv/trumicount) that has arguments containing "-" and uses strip_names=TRUE. What makes the matter worse is that there is no easy way to un-break the code without breaking it for earlier versions of docopt. Please don't merge such breaking changes in the future.

**Comment by edwindj** [comment]
Ah, sorry for the trouble and thanks for reporting!
